# Generated by Django 3.2.7 on 2021-09-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210929_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shop_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
