# Generated by Django 3.2.7 on 2021-09-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epic', models.CharField(max_length=20, unique=True)),
                ('name1', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('blck1', models.CharField(max_length=100)),
                ('blck2', models.CharField(default='', max_length=100)),
                ('subblock', models.CharField(max_length=100)),
                ('address1', models.CharField(blank=True, max_length=250, null=True)),
                ('address2', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(max_length=100)),
                ('birth', models.DateField(blank=True, null=True)),
                ('gname1', models.CharField(max_length=100)),
                ('gname2', models.CharField(max_length=100)),
                ('partno', models.CharField(max_length=100)),
                ('partname1', models.CharField(max_length=100)),
                ('partname2', models.CharField(default='', max_length=100)),
                ('serialno', models.CharField(max_length=100)),
                ('guardian_title', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='voter.png', upload_to='photos/')),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='barcodes/')),
            ],
        ),
    ]
