# Generated by Django 3.2.7 on 2021-09-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_voter_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='barcodes/'),
        ),
    ]
