# Generated by Django 3.2.7 on 2021-09-26 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20210926_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voter',
            name='epic',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='PANCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=255)),
                ('fname', models.CharField(max_length=255)),
                ('birth', models.DateField()),
                ('photo', models.ImageField(upload_to='pan/photos/')),
                ('sign', models.ImageField(upload_to='pan/signs/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
