# Generated by Django 3.2.7 on 2021-09-14 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_voter_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='birth',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
