# Generated by Django 3.2.7 on 2021-09-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_voter_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='voter',
            name='address2',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
