# Generated by Django 3.2.7 on 2021-09-18 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210914_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='polling_station',
            new_name='guardian_title',
        ),
    ]
