# Generated by Django 3.2.7 on 2021-09-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_polling_station_voter_guardian_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='photo',
            field=models.ImageField(default='voter.png', upload_to='photos/'),
        ),
    ]
