# Generated by Django 3.2.7 on 2021-09-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_pancard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='block',
            new_name='blck1',
        ),
        migrations.AddField(
            model_name='voter',
            name='blck2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
